name: Deploy NonProd

on:
  push:
    # branches:
    #   - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: nonprod
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: (NonProd) Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-southeast-2

      - name: (NonProd) Dry Run Deployment to Validate Files
        run: |
          ./scripts/deploy.sh --project "$PWD/map-series/" --tag ${{ github.sha }} --target s3://linz-topography-nonprod/qgis/

      - name: (NonProd) Upload QGIS Projects to S3
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          ./scripts/deploy.sh --project "$PWD/map-series/" --tag ${{ github.sha }} --target s3://linz-topography-nonprod/qgis/ --commit
          ./scripts/deploy.sh --project "$PWD/map-series/" --tag latest --githash ${{ github.sha }} --target s3://linz-topography-nonprod/qgis/ --commit
